# Generated by Django 2.2.3 on 2019-08-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(choices=[('1', 'CEO'), ('2', 'manage'), ('3', 'staff')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_married',
            field=models.CharField(choices=[('1', 'YES'), ('0', 'NO'), ('2', 'unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', 'men'), ('0', 'female'), ('2', 'unknown')], max_length=10),
        ),
    ]
