# Generated by Django 2.2.3 on 2019-08-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190805_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', 'male'), ('0', 'female'), ('2', 'unknown')], max_length=10),
        ),
    ]
