# Generated by Django 2.2.3 on 2019-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190805_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\J\\Desktop\\GAVEE\\docofgavee/MEDIA/', verbose_name='头像'),
        ),
    ]
