# Generated by Django 2.2.3 on 2019-08-06 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0018_auto_20190805_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, default='1970/11/11', null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('is_married', models.CharField(choices=[('1', 'YES'), ('0', 'NO'), ('2', 'unknown')], max_length=10)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(choices=[('1', 'male'), ('0', 'female'), ('2', 'unknown')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon', verbose_name='头像')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='资料', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
