# Generated by Django 2.2.4 on 2019-08-15 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190806_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
